import type { InvestigationTableDefinition } from "../../core/types/InvestigationTable";

/**
 * Declarative investigation-grid definition for the Message Investigation Workspace, consumed by
 * the shared {@link module:com/middlewareops/integrationportal/library/controls/InvestigationGrid}.
 * Adding, reordering, pinning or grouping a column is a change here only — no view edit (§ Display
 * Columns — "Every column should be configurable").
 */
export const messageInvestigationTableConfig: InvestigationTableDefinition = {
  columns: [
    {
      property: "severity",
      labelKey: "column.severity",
      type: "severity",
      width: "4rem",
      pinnable: true,
    },
    {
      property: "status",
      labelKey: "column.status",
      type: "status",
      sortable: true,
      width: "9rem",
      pinnable: true,
    },
    {
      property: "integrationFlow",
      labelKey: "column.integrationFlow",
      type: "text",
      sortable: true,
      filterable: true,
      groupable: true,
      quickSearchable: true,
      width: "16rem",
      pinnable: true,
    },
    {
      property: "applicationId",
      labelKey: "column.applicationId",
      type: "text",
      sortable: true,
      filterable: true,
      groupable: true,
      quickSearchable: true,
      width: "10rem",
    },
    {
      property: "messageId",
      labelKey: "column.messageId",
      type: "text",
      sortable: true,
      quickSearchable: true,
      width: "13rem",
    },
    {
      property: "mplId",
      labelKey: "column.mplId",
      type: "text",
      width: "13rem",
      visible: false,
    },
    {
      property: "correlationId",
      labelKey: "column.correlationId",
      type: "text",
      quickSearchable: true,
      width: "13rem",
      visible: false,
    },
    // Framework identity and recovery condition are two independent axes, so they are two columns —
    // never one fused value. Both are backend-derived; the grid only renders them.
    {
      property: "framework",
      labelKey: "column.framework",
      type: "text",
      sortable: true,
      filterable: true,
      groupable: true,
      quickSearchable: true,
      width: "11rem",
    },
    {
      property: "recoveryState",
      labelKey: "column.recoveryState",
      type: "text",
      sortable: true,
      filterable: true,
      groupable: true,
      width: "12rem",
    },
    {
      property: "messageType",
      labelKey: "column.sapMessageType",
      type: "text",
      sortable: true,
      filterable: true,
      groupable: true,
      width: "9rem",
    },
    {
      property: "sender",
      labelKey: "column.sapSender",
      type: "text",
      sortable: true,
      filterable: true,
      groupable: true,
      quickSearchable: true,
      width: "12rem",
    },
    {
      property: "receiver",
      labelKey: "column.sapReceiver",
      type: "text",
      sortable: true,
      filterable: true,
      groupable: true,
      quickSearchable: true,
      width: "12rem",
    },
    {
      property: "customStatus",
      labelKey: "column.customStatus",
      type: "text",
      sortable: true,
      filterable: true,
      groupable: true,
      width: "10rem",
      visible: false,
    },
    {
      property: "processingTimeHuman",
      labelKey: "column.processingTime",
      type: "text",
      align: "End",
      width: "9rem",
    },
    {
      property: "startTime",
      labelKey: "column.startTime",
      type: "date",
      sortable: true,
      width: "12rem",
    },
    {
      property: "endTime",
      labelKey: "column.endTime",
      type: "date",
      sortable: true,
      width: "12rem",
      visible: false,
    },
    {
      property: "payloadSizeBytes",
      labelKey: "column.payloadSize",
      type: "size",
      align: "End",
      width: "8rem",
      visible: false,
    },
    {
      property: "attachmentCount",
      labelKey: "column.attachmentCount",
      type: "number",
      align: "End",
      width: "7rem",
      visible: false,
    },
    {
      property: "retryStatus",
      labelKey: "column.retryStatus",
      type: "text",
      filterable: true,
      groupable: true,
      width: "9rem",
      visible: false,
    },
    {
      property: "queueName",
      labelKey: "column.queue",
      type: "text",
      groupable: true,
      width: "10rem",
      visible: false,
    },
    {
      property: "environment",
      labelKey: "column.environment",
      type: "text",
      groupable: true,
      width: "8rem",
      visible: false,
    },
    {
      property: "tenantId",
      labelKey: "column.tenant",
      type: "text",
      width: "8rem",
      visible: false,
    },
  ],
  defaultSortProperty: "startTime",
  defaultSortDescending: true,
};
